meta_product_name: "G&A Cleaning Pro Services"
meta_title: "G&A Cleaning Pro Services - Le service de nettoyage à l'écoute de vos besoins."
meta_description: "nettoyage de bureaux et locaux professionnels, copropriétés et espaces communs, interventions spécialisées et entretien espaces verts"
meta_image: "color-logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
